# Generated by Django 2.2.2 on 2019-10-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='location',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='school',
            name='principle',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
